name: whwwaterdata
channels:  
  - conda-forge
  - defaults
dependencies:
  - python
  - ipython
  - ipykernel
  - nb_conda_kernels
  - pip
  - requests
  - geopandas
  - descartes
  - geojson
  - rasterio
  - netcdf4
  - xarray
  - rioxarray
  - regionmask
  - dask
  - owslib
  - xlrd
  - boto3 # why wasn't it already in this env file? Oversight?
  - matplotlib
  - seaborn
  - cartopy
  - folium
  - contextily
  - ulmo
  - hydrodata
#   - pip:
#     - streamstats
